image: node:lts-alpine 

pages:
  cache:
    paths:
    - node_modules/
    
  stage: deploy
  script:
  - yarn install
  - yarn build
  - rm -rf public
  - mv build public
  artifacts:
    paths:
    - public
  only:
  - main