name: make

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: make yarn cmd=install

    - name: Build 
      run: make yarn cmd=build
